# Generated by Django 5.1.3 on 2024-12-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='hamburguesas/'),
        ),
    ]
